framework:
    messenger:
        transports:
            logs_ingest:
                dsn: '%env(RABBITMQ_DSN)%'
                options:
                    exchange:
                        name: logs
                        type: direct
                    queues:
                        logs.ingest:
                            binding_keys: ['logs.ingest']
                            arguments:
                                x-max-priority: 10
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
        routing:
            'App\Message\LogMessage': logs_ingest
